import {beforeEach,describe,expect,it,vi} from 'vitest';
import {fillSafe,undoLastFill} from '../src/core/filler';
import {DictionaryDetector} from '../src/core/detector';

describe('aggressive but bounded filler',()=>{
 beforeEach(()=>document.body.innerHTML='');
 it('触发 input/change/blur 并可撤销',()=>{document.body.innerHTML='<label>姓名<input value="旧值"></label>';const el=document.querySelector('input')!;const input=vi.fn(),change=vi.fn(),blur=vi.fn();el.addEventListener('input',input);el.addEventListener('change',change);el.addEventListener('blur',blur);const matches=new DictionaryDetector().scan(document);expect(fillSafe(matches,{name:'张三'})).toBe(1);expect(el.value).toBe('张三');expect(input).toHaveBeenCalled();expect(change).toHaveBeenCalled();expect(blur).toHaveBeenCalled();expect(undoLastFill()).toBe(1);expect(el.value).toBe('旧值');});
 it('默认填写身份证、期望薪资等已识别资料',()=>{document.body.innerHTML='<label>身份证号码<input></label><label>期望薪资<input></label>';const matches=new DictionaryDetector().scan(document);expect(fillSafe(matches,{idNumber:'430000000000000000',expectedSalary:'20k'})).toBe(2);expect([...document.querySelectorAll('input')].map(x=>x.value)).toEqual(['430000000000000000','20k']);});
 it('绝不填写密码、文件或触发提交',()=>{document.body.innerHTML='<form><label>密码<input type="password"></label><label>上传简历<input type="file"></label><button type="submit">提交</button></form>';const submit=vi.fn();document.querySelector('form')!.addEventListener('submit',submit);const matches=new DictionaryDetector().scan(document);expect(fillSafe(matches,{password:'secret'})).toBe(0);expect(submit).not.toHaveBeenCalled();});
});

describe('complex controls',()=>{beforeEach(()=>document.body.innerHTML='');it('填写原生下拉与单选',()=>{document.body.innerHTML='<label>最高学历<select><option>本科</option><option>硕士</option></select></label><fieldset>性别<label><input type="radio" name="g" value="男">男</label><label><input type="radio" name="g" value="女">女</label></fieldset>';const matches=new DictionaryDetector().scan(document);expect(fillSafe(matches,{education:'硕士',gender:'女'})).toBe(2);expect(document.querySelector('select')!.value).toBe('硕士');expect((document.querySelector('input[value="女"]') as HTMLInputElement).checked).toBe(true);});it('使用原生 setter 支持受控输入并触发事件',()=>{document.body.innerHTML='<label>所在城市<input></label>';const el=document.querySelector('input')!;const input=vi.fn();el.addEventListener('input',input);expect(fillSafe(new DictionaryDetector().scan(document),{currentCity:'长沙'})).toBe(1);expect(el.value).toBe('长沙');expect(input).toHaveBeenCalledOnce();});});

describe('undo transactions',()=>{beforeEach(()=>document.body.innerHTML='');it('只撤销最近一次填写操作',()=>{document.body.innerHTML='<label>姓名<input></label><label>手机号<input></label>';const matches=new DictionaryDetector().scan(document);expect(fillSafe(matches,{name:'张三'},matches.find(x=>x.key==='name')!.elementId)).toBe(1);expect(fillSafe(matches,{phone:'13800000000'},matches.find(x=>x.key==='phone')!.elementId)).toBe(1);expect(undoLastFill()).toBe(1);const inputs=document.querySelectorAll('input');expect(inputs[0].value).toBe('张三');expect(inputs[1].value).toBe('');expect(undoLastFill()).toBe(1);expect(inputs[0].value).toBe('');});});
