import type { EducationEntry, Profile } from '../core/types';
import { emptyEducation, migrateLegacyEducation } from '../core/profile';

const generalFields=[['name','姓名'],['phone','手机号'],['email','邮箱'],['currentCity','所在城市'],['gender','性别'],['birthDate','出生日期'],['politicalStatus','政治面貌'],['ethnicity','民族'],['github','GitHub'],['homepage','个人主页'],['portfolio','作品集'],['jobDirection','求职方向'],['source','信息来源'],['expectedCity','期望城市（每次确认）'],['acceptTransfer','是否接受调剂（每次确认）'],['acceptOtherRole','是否接受其他岗位（每次确认）'],['expectedSalary','期望薪资（每次确认）'],['relativeEmployed','是否有亲属任职（每次确认）'],['nonCompete','是否签署竞业协议（每次确认）']] as const;
const educationFields=[['school','学校'],['college','学院'],['major','专业'],['education','学历'],['enrollmentDate','入学时间'],['graduationDate','毕业时间']] as const;
const form=document.querySelector<HTMLFormElement>('#profile')!;
form.innerHTML=`<section><h2>基本资料</h2><div class="field-grid">${generalFields.map(([k,l])=>`<label>${l}<input name="${k}" autocomplete="off"></label>`).join('')}</div></section><section><div class="section-title"><div><h2>教育经历</h2><small>请按招聘页面通常显示的顺序排列，例如本科在前、硕士在后。</small></div><button type="button" id="add-education">添加教育经历</button></div><div id="educations"></div></section>`;
const educationRoot=document.querySelector<HTMLElement>('#educations')!;
function escapeAttribute(value:string){return value.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
function renderEducations(entries:EducationEntry[]){educationRoot.innerHTML=entries.map((entry,index)=>`<fieldset class="education-entry" data-index="${index}"><legend>教育经历 ${index+1}</legend><button type="button" class="remove-education" aria-label="删除教育经历 ${index+1}">删除</button><div class="field-grid">${educationFields.map(([k,l])=>`<label>${l}<input name="educations.${index}.${k}" value="${escapeAttribute(entry[k])}" autocomplete="off"></label>`).join('')}</div></fieldset>`).join('');}
function readEducations():EducationEntry[]{return [...educationRoot.querySelectorAll<HTMLElement>('.education-entry')].map(row=>Object.fromEntries(educationFields.map(([key])=>[key,(row.querySelector<HTMLInputElement>(`[name$=".${key}"]`)?.value??'').trim()])) as unknown as EducationEntry);}
void chrome.storage.local.get('profile').then(({profile={}}:{profile?:Profile})=>{for(const [key] of generalFields)(form.elements.namedItem(key) as HTMLInputElement).value=typeof profile[key]==='string'?profile[key] as string:'';renderEducations(migrateLegacyEducation(profile));});
document.querySelector('#add-education')!.addEventListener('click',()=>renderEducations([...readEducations(),emptyEducation()]));
educationRoot.addEventListener('click',event=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('.remove-education');if(!button)return;const entries=readEducations();entries.splice(Number(button.closest<HTMLElement>('.education-entry')!.dataset.index),1);renderEducations(entries.length?entries:[emptyEducation()]);});
form.onsubmit=async event=>{event.preventDefault();const data=new FormData(form);const profile:Profile={educations:readEducations().filter(entry=>Object.values(entry).some(Boolean))};for(const [key] of generalFields)profile[key]=String(data.get(key)??'').trim();await chrome.storage.local.set({profile});document.querySelector('#status')!.textContent='已保存到本机浏览器';};
