import { EDUCATION_KEYS, type EducationKey, type FieldMatch, type FillChange, type Profile, type ProfileKey } from './types';
const transactions:FillChange[][]=[]; let activeTransaction:FillChange[]|undefined;
function setNative(el:HTMLInputElement|HTMLTextAreaElement,value:string){ const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype; const setter=Object.getOwnPropertyDescriptor(proto,'value')?.set; setter?.call(el,value); }
function fire(el:HTMLElement){ el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'})); el.dispatchEvent(new Event('change',{bubbles:true})); el.dispatchEvent(new FocusEvent('blur',{bubbles:true})); }
export function fillElement(el:HTMLElement,value:string|boolean,key:ProfileKey):boolean { if(el instanceof HTMLInputElement && ['file','password','submit','button'].includes(el.type)) return false; if(el instanceof HTMLInputElement&&el.type==='radio'&&![el.value,el.labels?.[0]?.textContent?.trim()].includes(String(value)))return false; const previous=el instanceof HTMLInputElement&&['checkbox','radio'].includes(el.type)?el.checked:(el as HTMLInputElement).value??el.textContent??''; const change={element:el,previous,key}; activeTransaction?.push(change);
 if(el instanceof HTMLSelectElement){ const option=[...el.options].find(o=>o.value===String(value)||o.text.trim()===String(value)); if(!option){activeTransaction?.pop();return false;} el.value=option.value; }
 else if(el instanceof HTMLInputElement && ['checkbox','radio'].includes(el.type)){el.checked=typeof value==='boolean'?value:[el.value,el.labels?.[0]?.textContent?.trim()].includes(String(value));}
 else if(el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement) setNative(el,String(value)); else if(el.isContentEditable) el.textContent=String(value); else {activeTransaction?.pop();return false;} fire(el); return true; }
export function profileValue(profile:Profile,match:FieldMatch):string|boolean|undefined {if(match.key&&EDUCATION_KEYS.includes(match.key as EducationKey)){const entry=profile.educations?.[match.educationIndex??0];const value=entry?.[match.key as EducationKey];if(value!==undefined&&value!=='')return value;}const legacy=match.key?profile[match.key]:undefined;return typeof legacy==='string'||typeof legacy==='boolean'?legacy:undefined;}
export function fillSafe(matches:FieldMatch[],profile:Profile,oneId?:string,allowConfirmed=false):number { let count=0; activeTransaction=[]; for(const m of matches){const allowed=m.policy==='auto'&&m.confidence>=.8||allowConfirmed&&oneId===m.elementId&&m.policy==='confirm'&&m.confidence>=.8;if(!allowed||!m.key||(oneId&&m.elementId!==oneId))continue; const value=profileValue(profile,m); if(value===undefined||value==='')continue; const el=[...document.querySelectorAll<HTMLElement>('[data-job-helper-id]')].find(x=>x.dataset.jobHelperId===m.elementId); if(el&&fillElement(el,value,m.key))count++;} if(activeTransaction.length)transactions.push(activeTransaction);activeTransaction=undefined;return count;}
export function undoLastFill():number {let n=0; const changes=transactions.pop()??[]; while(changes.length){const c=changes.pop()!; if(!c.element.isConnected)continue; if(c.element instanceof HTMLInputElement&&['checkbox','radio'].includes(c.element.type))c.element.checked=Boolean(c.previous); else if(c.element instanceof HTMLInputElement||c.element instanceof HTMLTextAreaElement)setNative(c.element,String(c.previous)); else c.element.textContent=String(c.previous); fire(c.element);n++;}return n;}
